export const CREATE_TOMATO = "CREATE_TOMATO";
export const LOAD_CONTEXTS_SUCCESS = "LOAD_CONTEXTS_SUCCESS";
export const LOAD_USER_BY_ID = "LOAD_USER_BY_ID";
export const LOAD_USER_BY_ID_SUCCESS = "LOAD_USER_BY_ID_SUCCESS";
export const SAVE_CONTEXT_SUCCESS = "SAVE_CONTEXT_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
